"use client";
import { useState, type ReactNode } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, CalendarDays, MapPin, Users, Wrench, ClipboardList, ShieldCheck, FileText, Package, UserCheck, CheckCircle2, AlertTriangle, type LucideIcon } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import WorkflowAttachments from "./WorkflowAttachments";
import { useEventRecords, emptyEvent, saveEventRecord, validateEvent, blockedTime, type EventRecord, type EventTimes, type Category, type Status, type ApprovalState, type DocStatus } from "@/lib/eventPageStore";
const input="mt-2 w-full min-h-10 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-normal text-slate-700 focus:border-[#155ca7] focus:outline-none focus:ring-1 focus:ring-[#155ca7]";
const button="rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50";
const primary="rounded-xl bg-[#0C2F57] px-4 py-2 text-sm font-semibold text-white hover:brightness-110";
type TemplateProps = { templateInitial?: EventRecord; templateTitle?: string; templateInstructions?: string; onTemplateSave?: (layout: EventRecord) => void };
type Tab="Overview"|"Docs"|"Logistics"|"Review";
function Section({icon:Icon,title,subtitle,children}:{icon:LucideIcon;title:string;subtitle?:string;children:ReactNode}) {return <Card><CardContent className="p-5"><div className="flex items-start gap-2"><Icon className="mt-0.5 h-5 w-5 shrink-0 text-slate-500" aria-hidden="true"/><div><h2 className="text-lg font-bold text-slate-900">{title}</h2>{subtitle && <p className="mt-1 text-sm text-slate-600">{subtitle}</p>}</div></div><div className="mt-4 space-y-3">{children}</div></CardContent></Card>;}
function Summary({icon:Icon,title,children}:{icon:LucideIcon;title:string;children:ReactNode}) {return <Card><CardContent className="p-5"><div className="flex items-start gap-3"><Icon className="h-5 w-5 shrink-0 text-slate-500" aria-hidden="true"/><div><p className="text-sm font-semibold text-slate-900">{title}</p><div className="mt-1 text-sm text-slate-600">{children}</div></div></div></CardContent></Card>;}
function Field({label,value,onChange,type="text",options,area=false,scope=""}:{label:string;value:string;onChange:(value:string)=>void;type?:string;options?:readonly string[];area?:boolean;scope?:string}) {const accessible=scope?`${scope}: ${label}`:label;return <label className="block text-sm font-semibold text-slate-900">{label}{options?<select aria-label={accessible} className={input} value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select>:area?<textarea aria-label={accessible} rows={3} className={input} value={value} onChange={e=>onChange(e.target.value)}/>:<input aria-label={accessible} type={type} className={input} min={type==="number"?0:undefined} step={type==="number"?1:undefined} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
const row="rounded-xl border border-slate-100 bg-white p-3 space-y-3";
const grid="grid gap-3 sm:grid-cols-2";
export default function EventEditor({mode,eventId,preview=false,onClose,...templateProps}:{mode:"new"|"edit";eventId?:string;preview?:boolean;onClose?:()=>void} & TemplateProps) {
 const {records,ready}=useEventRecords();const event=records.find(e=>e.id===eventId);
 if(!ready) return <p className="p-6" role="status">Loading event form…</p>;
 if(mode==="edit"&&!event) return <div className="p-6"><h1 className="text-xl font-bold">Event not found</h1><Link href="/facilities/events-control">Back to Events Control</Link></div>;
 return <EventForm key={eventId||"new"} initial={templateProps.templateInitial || event||emptyEvent()} mode={mode} preview={preview} onClose={onClose} {...templateProps}/>;
}
function EventForm({initial,mode,preview,onClose,templateTitle,templateInstructions,onTemplateSave}:{initial:EventRecord;mode:"new"|"edit";preview:boolean;onClose?:()=>void} & TemplateProps) {
 const router=useRouter();const [draft,setDraft]=useState(initial);const [tab,setTab]=useState<Tab>("Overview");const [error,setError]=useState("");
 const patch=(values:Partial<EventRecord>)=>setDraft(prev=>({...prev,...values}));
 function updateRow<K extends "documents"|"equipment"|"staffing"|"approvals"|"timeline"|"internalNotes">(key:K,index:number,values:Partial<EventRecord[K][number]>) {setDraft(prev=>({...prev,[key]:prev[key].map((item,i)=>i===index?{...item,...values}:item)}));}
 function removeRow(key:"documents"|"equipment"|"staffing"|"timeline"|"internalNotes",index:number) {setDraft(prev=>({...prev,[key]:prev[key].filter((_,i)=>i!==index)}));}
 const time=(label:string,key:keyof EventTimes)=><Field label={label} type="datetime-local" value={draft.times[key]} onChange={value=>patch({times:{...draft.times,[key]:value}})}/>;
 const noteRows=(key:"timeline"|"internalNotes")=><>{draft[key].map((n,i)=><div key={i} className={row}><div className={key === "internalNotes" ? "grid gap-3" : grid}><Field scope={`${key} ${i+1}`} label="By" value={n.by} onChange={by=>updateRow(key,i,{by})}/><Field scope={`${key} ${i+1}`} label="Date & time" type="datetime-local" value={n.at.replace(" ","T")} onChange={at=>updateRow(key,i,{at})}/></div><Field scope={`${key} ${i+1}`} label={key==="timeline"?"Action / update":"Internal note"} area value={n.text} onChange={text=>updateRow(key,i,{text})}/><button type="button" className={button} onClick={()=>removeRow(key,i)}>Remove {key==="timeline"?"entry":"note"} {i+1}</button></div>)}<button type="button" className={button} onClick={()=>patch({[key]:[...draft[key],{by:"",at:"",text:""}]})}>{key==="timeline"?"Add timeline entry":"Add internal note"}</button></>;
 function save() {if(onTemplateSave) { onTemplateSave(draft); return; } if(preview)return;const problem=validateEvent(draft);if(problem){setError(problem);if(/Equipment/.test(problem))setTab("Logistics");else setTab("Overview");window.scrollTo({top:0,behavior:"smooth"});return;}try{const id=draft.id||`event-${crypto.randomUUID()}`;saveEventRecord({...draft,id});router.push(`/facilities/events-control/${id}`);}catch {setError("The event could not be saved in this browser. Storage may be full or unavailable. Your entries are still here; try removing large attachments.");}}
 return <form noValidate onSubmit={e=>{e.preventDefault();save();}} className="mx-auto w-full max-w-7xl px-4 pb-12 pt-8 text-slate-900 sm:px-6 lg:px-8">
  <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div>
   {preview ? <button type="button" className={button} onClick={onClose}>Back to forms</button> : <Link className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-900" href={mode==="edit"?`/facilities/events-control/${initial.id}`:"/facilities/events-control"}><ArrowLeft className="h-4 w-4"/> {mode==="edit"?"Back to event record":"Back to Events Control"}</Link>}
   <p className="mt-4 text-xs font-bold uppercase tracking-[0.2em] text-[#155ca7]">Facilities Department · Event form</p><h1 className="mt-2 text-4xl font-extrabold text-[#0C2F57]">{onTemplateSave ? "Edit Event Form Template" : preview ? (templateTitle || "Event Form Preview") :mode==="edit"?"Edit Event":"Create Event"}</h1><p className="mt-2 text-slate-600">Capture plans, approvals, logistics and learnings in one event record.</p></div>
   {!preview && <div className="flex gap-2"><Link className={button} href={mode==="edit"?`/facilities/events-control/${initial.id}`:"/facilities/events-control"}>Cancel</Link><button type="submit" className={primary}>Save event</button></div>}
  </div>
  <p className="mt-4 rounded-xl border border-[#cce2fc] bg-[#eef6ff] px-4 py-3 text-sm text-[#35557f]">{preview?"Preview only · try the fields and tabs. Closing this preview discards these answers; no event is created.":"Design preview · Save event keeps your entries and attachments in this browser. Statuses and sign-offs are design fields; no live approval is granted."}</p>
  {templateInstructions && <p className="mt-4 text-sm text-slate-700">{templateInstructions}</p>}
  {onTemplateSave && <p className="mt-4 text-sm text-slate-600">Configure reusable defaults, document requirements, equipment and staffing rows in the original four-tab layout. Saving updates the template, without creating or changing an event record.</p>}
  {error && <p role="alert" className="mt-4 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
  <Card className="mt-6"><CardContent className="p-5"><div className={grid}><Field label="Event name" value={draft.name} onChange={name=>patch({name})}/><Field label="Category" options={["Concert","Stand-up","Community","Cultural","Other"]} value={draft.category} onChange={category=>patch({category:category as Category})}/><Field label="Event summary" area value={draft.quickNotes} onChange={quickNotes=>patch({quickNotes})}/><Field label="Venue / facility and space" value={draft.location} onChange={location=>patch({location})}/><Field label="Organising group" value={draft.organiser} onChange={organiser=>patch({organiser})}/>{(["name","email","phone"] as const).map(key=><Field key={key} label={`Lead organiser ${key}`} type={key==="email"?"email":key==="phone"?"tel":"text"} value={draft.leadOrganiser[key]} onChange={v=>patch({leadOrganiser:{...draft.leadOrganiser,[key]:v}})}/>)}<Field label="Status" options={["Draft","Submitted","Approved","Completed","Cancelled"]} value={draft.status} onChange={status=>patch({status:status as Status})}/></div></CardContent></Card>
  <div className="mt-6 grid gap-4 lg:grid-cols-4">
   <Summary icon={CalendarDays} title="Event window">{draft.times.eventStart.replace("T"," · ") || "Not set"} → {draft.times.eventEnd.replace("T"," · ") || "Not set"}</Summary>
   <Summary icon={MapPin} title="Venue">{draft.location || "Not set"}</Summary>
   <Summary icon={Users} title="Organiser">{draft.organiser || "Not set"}<p className="mt-1 text-xs text-slate-500">Lead: {draft.leadOrganiser.name || "Not set"} · {draft.leadOrganiser.email}</p></Summary>
   <Summary icon={Wrench} title="Venue blocked">{blockedTime(draft.times)}<p className="mt-1 text-xs text-slate-500">Prep start → dismantle complete</p></Summary>
  </div>
  <nav aria-label="Event form sections" className="mt-6 flex flex-wrap gap-2">{(["Overview","Docs","Logistics","Review"] as const).map(value=><button key={value} type="button" aria-pressed={tab===value} className={tab===value?primary:button} onClick={()=>setTab(value)}>{value}</button>)}</nav>
  <div className="mt-4 grid gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2">
   {tab==="Overview" && <>
    <Section icon={Wrench} title="Venue Impact" subtitle="Track true facility downtime so scheduling avoids clashes."><div className={grid}>{time("Prep start","prepStart")}{time("Doors open","doorsOpen")}{time("Event start","eventStart")}{time("Event end","eventEnd")}{time("Dismantle complete","dismantleComplete")}</div><p className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700"><strong>Why this matters:</strong> venue availability is impacted before guests arrive and continues after the event ends. All dates and times are Gibraltar local time.</p></Section>
    <Section icon={ClipboardList} title="Timeline" subtitle="Key actions and changes for review.">{noteRows("timeline")}</Section>
    <Section icon={ShieldCheck} title="Approvals" subtitle="Capture sign-off per area: safeguarding, facilities/venue, equipment and final.">{draft.approvals.map((a,i)=><div key={i} className={row}><h3 className="text-sm font-semibold">{a.area}</h3><div className={grid}><Field scope={a.area} label="Approval state" options={["Pending","Approved","Not required"]} value={a.state} onChange={state=>updateRow("approvals",i,{state:state as ApprovalState})}/><Field scope={a.area} label="Signed off by" value={a.by==="—"?"":a.by} onChange={by=>updateRow("approvals",i,{by})}/><Field scope={a.area} label="Sign-off date" type="date" value={a.at==="—"?"":a.at} onChange={at=>updateRow("approvals",i,{at})}/></div></div>)}</Section>
   </>}
   {tab==="Docs" && <Section icon={FileText} title="Plans & Documentation" subtitle="Attach plans and capture their owner, review status and comments.">{draft.documents.map((d,i)=><div key={i} className={row}><Field scope={`Document ${i+1}`} label="Document name" value={d.name} onChange={name=>updateRow("documents",i,{name})}/><div className={grid}><Field scope={`Document ${i+1}`} label="Owner" value={d.owner} onChange={owner=>updateRow("documents",i,{owner})}/><Field scope={`Document ${i+1}`} label="Updated" type="date" value={d.updated} onChange={updated=>updateRow("documents",i,{updated})}/><Field scope={`Document ${i+1}`} label="Review status" options={["Pending","Approved","Rejected"]} value={d.status} onChange={status=>updateRow("documents",i,{status:status as DocStatus})}/></div><Field scope={`Document ${i+1}`} label="Notes" area value={d.notes} onChange={notes=>updateRow("documents",i,{notes})}/><Field scope={`Document ${i+1}`} label="Review comments" area value={d.comments} onChange={comments=>updateRow("documents",i,{comments})}/><WorkflowAttachments label={`Files: ${d.name||`Document ${i+1}`}`} value={d.files} onChange={files=>updateRow("documents",i,{files})}/><button type="button" className={button} onClick={()=>removeRow("documents",i)}>Remove document {i+1}</button></div>)}<button type="button" className={button} onClick={()=>patch({documents:[...draft.documents,{name:"",owner:"",updated:"",status:"Pending",notes:"",comments:"",files:[]}]})}>Add document</button></Section>}
   {tab==="Logistics" && <>
    <Section icon={Package} title="Equipment & Resources" subtitle="Requested items, quantities, provider and approval state.">{draft.equipment.map((x,i)=><div key={i} className={row}><div className={grid}><Field scope={`Equipment ${i+1}`} label="Item" value={x.item} onChange={item=>updateRow("equipment",i,{item})}/><Field scope={`Equipment ${i+1}`} label="Quantity" type="number" value={String(x.qty)} onChange={qty=>updateRow("equipment",i,{qty:Number(qty)})}/><Field scope={`Equipment ${i+1}`} label="Provided by" value={x.providedBy} onChange={providedBy=>updateRow("equipment",i,{providedBy})}/><Field scope={`Equipment ${i+1}`} label="Approval state" options={["Pending","Approved","Not required"]} value={x.state} onChange={state=>updateRow("equipment",i,{state:state as ApprovalState})}/></div><Field scope={`Equipment ${i+1}`} label="Notes" area value={x.notes} onChange={notes=>updateRow("equipment",i,{notes})}/><button type="button" className={button} onClick={()=>removeRow("equipment",i)}>Remove equipment {i+1}</button></div>)}<button type="button" className={button} onClick={()=>patch({equipment:[...draft.equipment,{item:"",qty:0,providedBy:"",state:"Pending",notes:""}]})}>Add equipment</button></Section>
    <Section icon={UserCheck} title="Staffing & Roles" subtitle="Capture responsibilities so setup is repeatable next time.">{draft.staffing.map((s,i)=><div key={i} className={row}><div className={grid}><Field scope={`Staff ${i+1}`} label="Role" value={s.role} onChange={role=>updateRow("staffing",i,{role})}/><Field scope={`Staff ${i+1}`} label="Name / team" value={s.name} onChange={name=>updateRow("staffing",i,{name})}/><Field scope={`Staff ${i+1}`} label="Confirmation status" options={["Pending","Confirmed","Not required"]} value={s.status} onChange={status=>updateRow("staffing",i,{status})}/></div><button type="button" className={button} onClick={()=>removeRow("staffing",i)}>Remove staff role {i+1}</button></div>)}<button type="button" className={button} onClick={()=>patch({staffing:[...draft.staffing,{role:"",name:"",status:"Pending"}]})}>Add staff role</button></Section>
   </>}
   {tab==="Review" && <Section icon={CheckCircle2} title="Post-Event Review" subtitle="Record learnings so future events can reuse what works."><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={draft.postEvent.available} onChange={e=>patch({postEvent:{...draft.postEvent,available:e.target.checked}})}/>Review recorded</label>{([["whatWorked","What worked well"],["whatDidnt","What didn’t work"],["issues","Issues encountered"],["recommendations","Recommendations next time"]] as const).map(([key,label])=><div key={key} className={row}><Field label={label} area value={draft.postEvent[key]} onChange={value=>patch({postEvent:{...draft.postEvent,[key]:value,available:true}})}/></div>)}</Section>}
  </div><aside className="space-y-4"><Section icon={AlertTriangle} title="Internal Notes" subtitle="Department notes alongside the event record.">{noteRows("internalNotes")}</Section><Section icon={ShieldCheck} title="Repeatability" subtitle="Capture learnings to make the next event easier."><div className={row}><h3 className="text-sm font-semibold">Suggested next step</h3><p className="text-sm text-slate-600">After the event, record what worked and what didn’t in Review.</p></div></Section></aside></div>
  {onTemplateSave && <div className="mt-6 flex justify-end"><button type="submit" className={primary}>Save form</button></div>}
  {!preview && <div className="mt-6 flex justify-end"><button type="submit" className={primary}>Save event</button></div>}
 </form>;
}
